---

- name: Import InfluxDB GPG key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    validate_certs: yes
    state: present

- name: Add InfluxDB repository
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu bionic stable
    validate_certs: yes
    state: present
    update_cache: yes

- name: Install Telegraf
  apt:
    name: telegraf
    state: latest

- name: Start Telegraf
  systemd:
    state: started
    name: telegraf